services:
  spring-api-docker-image:
    image: spring-api-docker-image
    container_name: spring-api-docker-image
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      - spring-network
    depends_on:
      - mysql
  mysql:
    image: mysql
    container_name: mysql-db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=dockerDB
      - MYSQL_USER=alopezo
      - MYSQL_PASSWORD=12345
    ports:
      - 3307:3306
    networks:
      - spring-network
    volumes:
      - mysql-data:/var/lib/mysql
networks:
  spring-network:
volumes:
  mysql-data: